# Generated by Django 3.2.5 on 2021-11-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarrif',
            name='id',
        ),
        migrations.AddField(
            model_name='tarrif',
            name='tarrifid',
            field=models.UUIDField(db_column='TarrifId', default='784b474d-ac08-4950-87cc-3fb15ee26598', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
