# Generated by Django 3.2.9 on 2021-11-10 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.SmallAutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
        migrations.CreateModel(
            name='Tarrif',
            fields=[
                ('tarrifid', models.UUIDField(db_column='TarrifId', primary_key=True, serialize=False)),
                ('fromtime', models.FloatField(blank=True, db_column='FromTime', null=True)),
                ('totime', models.FloatField(blank=True, db_column='ToTime', null=True)),
                ('cost', models.FloatField(blank=True, db_column='Cost', null=True)),
                ('initiatedby', models.CharField(blank=True, db_column='Initiatedby', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('lastupdate', models.DateField(blank=True, db_column='LastUpdate', null=True)),
                ('updatelog', models.CharField(blank=True, db_column='UpdateLog', max_length=50, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemApp.customers')),
            ],
        ),
    ]
