# Generated by Django 3.2.9 on 2021-11-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0003_parkinglog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkinglog',
            table='ParkingLog',
        ),
    ]
