# Generated by Django 3.2.9 on 2021-11-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0004_alter_parkinglog_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarrif',
            old_name='tarrifid',
            new_name='tarrif_id',
        ),
    ]
