# Generated by Django 3.2.9 on 2021-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0006_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phonenum',
            field=models.CharField(blank=True, db_column='PhoneNum', max_length=30, null=True),
        ),
    ]
