# Generated by Django 3.2.9 on 2021-11-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0007_users_phonenum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarrif',
            table='Tarrif',
        ),
        migrations.CreateModel(
            name='Subcriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(db_column='SubscriptionId', max_length=50)),
                ('platenumber', models.CharField(db_column='PlateNumber', max_length=50)),
                ('start_date', models.DateField(db_column='SubscriptionDate')),
                ('end_date', models.DateField(db_column='SubscriptionEndDate')),
                ('type', models.CharField(db_column='SubscriptionType', max_length=50)),
                ('amount', models.FloatField(db_column='SubscriptionAmount')),
                ('phonenum', models.CharField(db_column='ContactNumber', max_length=50)),
                ('office', models.CharField(db_column='OfficeLocation', max_length=50)),
                ('parklot', models.CharField(db_column='ParkingLot', max_length=50)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SystemApp.customers')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
    ]
