# Generated by Django 3.2.9 on 2021-11-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0008_auto_20211112_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
