# Generated by Django 3.2.9 on 2021-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0009_auto_20211112_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriptions',
            name='id',
        ),
        migrations.AlterField(
            model_name='subcriptions',
            name='end_date',
            field=models.DateField(db_column='end'),
        ),
        migrations.AlterField(
            model_name='subcriptions',
            name='start_date',
            field=models.DateField(db_column='start'),
        ),
        migrations.AlterField(
            model_name='subcriptions',
            name='subscription_id',
            field=models.BigAutoField(db_column='SubscriptionId', primary_key=True, serialize=False),
        ),
    ]
